from __future__ import annotations

import hashlib
import mimetypes
import os
from pathlib import Path
from typing import Optional
from urllib.parse import urlparse

import httpx
from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import FileResponse

router = APIRouter()

PROJECT_ROOT = Path(__file__).resolve().parents[2]
MEDIA_DIR = PROJECT_ROOT / ".local" / "media"
GENERATED_DIR = MEDIA_DIR / "generated"


def _normalize_remote_url(url: str) -> str:
    url = (url or "").strip()
    if not url:
        raise ValueError("empty_url")
    if url.startswith("//"):
        url = f"https:{url}"

    parsed = urlparse(url)
    if parsed.scheme not in {"http", "https"}:
        raise ValueError("invalid_scheme")
    if not parsed.netloc:
        raise ValueError("missing_host")

    host = (parsed.hostname or "").lower()
    if host in {"localhost", "127.0.0.1", "::1"}:
        raise ValueError("forbidden_host")

    return url


def _pick_extension(url: str, content_type: str) -> str:
    url_path = urlparse(url).path
    suffix = Path(url_path).suffix.lower()
    if suffix and len(suffix) <= 8:
        # Only allow common image extensions.
        if suffix in {".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp", ".svg"}:
            return suffix

    ct = (content_type or "").split(";")[0].strip().lower()
    if ct in {"image/svg+xml"}:
        return ".svg"
    guessed = mimetypes.guess_extension(ct) if ct else None
    if guessed and guessed.lower() in {".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp"}:
        return guessed.lower()
    return ".bin"


def _find_cached_file(media_id: str) -> Optional[Path]:
    if not MEDIA_DIR.exists():
        return None
    for p in MEDIA_DIR.glob(f"{media_id}.*"):
        if p.is_file():
            return p
    return None


def _is_safe_generated_filename(name: str) -> bool:
    name = (name or "").strip()
    if not name or "/" in name or "\\" in name or ".." in name:
        return False
    # We only serve files generated by this app. Use a strict format to avoid traversal.
    # - sha256 hex (64 chars) + ext
    # Note: allow short extensions like `.md` (64 + 1 + 2 = 67).
    if len(name) < 67:
        return False
    stem, dot, ext = name.rpartition(".")
    if dot != ".":
        return False
    if len(stem) != 64:
        return False
    if any(c not in "0123456789abcdef" for c in stem.lower()):
        return False
    return ext.lower() in {"svg", "png", "jpg", "jpeg", "gif", "webp", "bmp", "md", "tex", "pdf"}


@router.get("/media/generated/{filename}")
async def get_generated_media(filename: str) -> FileResponse:
    """Serve locally generated media from `.local/media/generated/`."""

    if not _is_safe_generated_filename(filename):
        raise HTTPException(status_code=400, detail="invalid_filename")

    path = (GENERATED_DIR / filename).resolve()
    try:
        path.relative_to(GENERATED_DIR.resolve())
    except Exception:
        raise HTTPException(status_code=400, detail="invalid_path")
    if not path.exists() or not path.is_file():
        raise HTTPException(status_code=404, detail="not_found")

    ext = path.suffix.lower().lstrip(".")
    if ext in {"md", "tex", "pdf"}:
        # Force "download" behavior for generated documents (avoid opening raw text/PDF in-app).
        return FileResponse(path, filename=filename)
    return FileResponse(path)


@router.get("/media/proxy")
async def proxy_media(url: str = Query(..., min_length=1, max_length=2000)) -> FileResponse:
    """
    Fetch a remote media URL and cache it on disk for stable rendering.

    - Returns a cached file if available.
    - Downloads and stores into `.local/media/` otherwise.
    """
    try:
        normalized = _normalize_remote_url(url)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))

    media_id = hashlib.sha256(normalized.encode("utf-8")).hexdigest()
    cached = _find_cached_file(media_id)
    if cached:
        return FileResponse(cached)

    MEDIA_DIR.mkdir(parents=True, exist_ok=True)

    try:
        max_bytes = int(os.getenv("MEDIA_PROXY_MAX_BYTES") or str(10 * 1024 * 1024))
    except Exception:
        max_bytes = 10 * 1024 * 1024
    max_bytes = max(256 * 1024, min(max_bytes, 200 * 1024 * 1024))

    async with httpx.AsyncClient(
        timeout=httpx.Timeout(30.0, connect=10.0),
        follow_redirects=True,
        headers={"User-Agent": "ExamPaperAssistant/1.0"},
    ) as client:
        try:
            async with client.stream("GET", normalized) as resp:
                if resp.status_code != 200:
                    raise HTTPException(status_code=502, detail=f"fetch_failed_status: {resp.status_code}")

                content_len = resp.headers.get("content-length") or ""
                try:
                    if content_len.strip() and int(content_len) > max_bytes:
                        raise HTTPException(status_code=413, detail="media_too_large")
                except ValueError:
                    pass

                ext = _pick_extension(normalized, resp.headers.get("content-type") or "")
                out_path = MEDIA_DIR / f"{media_id}{ext}"
                tmp_path = MEDIA_DIR / f"{media_id}{ext}.tmp"

                total = 0
                try:
                    with tmp_path.open("wb") as f:
                        async for chunk in resp.aiter_bytes():
                            if not chunk:
                                continue
                            total += len(chunk)
                            if total > max_bytes:
                                raise HTTPException(status_code=413, detail="media_too_large")
                            f.write(chunk)
                    tmp_path.replace(out_path)
                except HTTPException:
                    try:
                        tmp_path.unlink(missing_ok=True)
                    except Exception:
                        pass
                    raise
                except Exception as exc:
                    try:
                        tmp_path.unlink(missing_ok=True)
                    except Exception:
                        pass
                    raise HTTPException(status_code=502, detail=f"fetch_failed: {str(exc)}")
        except HTTPException:
            raise
        except Exception as exc:
            raise HTTPException(status_code=502, detail=f"fetch_failed: {str(exc)}")

    return FileResponse(out_path)

