from __future__ import annotations

import json
import os
from typing import Any, Dict, List, Optional

from backend.core.logging_utils import get_logger
from backend.core.settings import LESSON_PLAN_MAX_TOKENS, LESSON_PLAN_MODEL, LESSON_PLAN_TEMPERATURE
from backend.llm.client import is_llm_configured
from backend.question_library.gen_common import DEFAULT_SEARCH_CONFIG, _difficulty_instruction, _resolve_realize_temperature
from backend.question_library.gen_llm import _chat_json_with_reasoning, _extract_json_obj, _extract_json_value
from backend.question_library.gen_utils import ReasoningEventHandler
from backend.question_library.subject_knowledge import get_subject_bank, infer_subject_family

logger = get_logger(__name__)
_realize_max_tokens_invalid_logged = False


def _resolve_realize_max_tokens() -> int:
    raw = str(os.getenv("QUESTION_LIBRARY_REALIZE_MAX_TOKENS") or "").strip()
    if raw:
        try:
            return max(1, int(raw))
        except Exception:
            global _realize_max_tokens_invalid_logged
            if not _realize_max_tokens_invalid_logged:
                _realize_max_tokens_invalid_logged = True
                logger.warning(
                    "question_library_realize_max_tokens_invalid",
                    extra={"value": raw},
                    exc_info=True,
                )
    try:
        base = int(LESSON_PLAN_MAX_TOKENS or 0)
    except Exception:
        base = 0
    min_budget = int(DEFAULT_SEARCH_CONFIG.get("realize_min_max_tokens") or 5000)
    return max(base, min_budget)


def _normalize_question_text(value: Any) -> str:
    if isinstance(value, list):
        parts = [str(item or "").strip() for item in value if str(item or "").strip()]
        return "\n".join(parts).strip()
    return str(value or "").strip()


def _extract_question_items(payload: Any) -> List[dict]:
    if isinstance(payload, list):
        return [item for item in payload if isinstance(item, dict)]
    if not isinstance(payload, dict):
        return []

    for key in ("questions", "题目", "试题"):
        items = payload.get(key)
        if isinstance(items, list):
            return [item for item in items if isinstance(item, dict)]

    if any(key in payload for key in ("stem", "题干", "question", "answer", "答案", "analysis", "解析")):
        return [payload]
    return []


def _normalize_question_item(q: dict, spec: dict) -> Optional[dict]:
    if not isinstance(q, dict):
        return None

    stem = _normalize_question_text(q.get("stem") or q.get("题干") or q.get("question") or q.get("题目"))
    ans = _normalize_question_text(q.get("answer") or q.get("答案") or q.get("参考答案"))
    ana = _normalize_question_text(q.get("analysis") or q.get("解析") or q.get("解答"))
    if not stem or not ans or not ana:
        return None

    diagrams = q.get("diagrams")
    normalized_diagrams = diagrams if isinstance(diagrams, list) else None

    out = {
        "stem": stem,
        "answer": ans,
        "analysis": ana,
        "spec_id": str((spec or {}).get("spec_id") or "").strip(),
        "skill": str((spec or {}).get("skill") or "").strip(),
        "reasoning": str((spec or {}).get("reasoning") or "").strip(),
        "trap": str((spec or {}).get("trap") or "").strip(),
        "surface": str((spec or {}).get("surface") or "").strip(),
        "seed_tag": str((spec or {}).get("seed_tag") or "").strip(),
    }

    # Keep diagram payload when present (generated by diagram stage).
    if normalized_diagrams is not None:
        out["diagrams"] = [d for d in normalized_diagrams if isinstance(d, dict)][:6]

    return out


async def realize_drafts(
    spec: dict,
    *,
    source_pack: dict,
    n: int = 2,
    stream_reasoning: bool = False,
    on_reasoning_event: ReasoningEventHandler = None,
) -> List[dict]:
    if not is_llm_configured():
        return []

    subj = str((spec or {}).get("subject") or (source_pack or {}).get("subject") or "").strip() or "高中数学"
    topic = str((spec or {}).get("topic") or (source_pack or {}).get("topic") or "").strip()
    difficulty = str((spec or {}).get("difficulty") or "").strip()
    qtype = str((spec or {}).get("question_type") or "").strip()
    study_md = str((source_pack or {}).get("study_markdown") or "").strip()
    n = max(1, min(int(n or 1), 4))

    model = str(LESSON_PLAN_MODEL or "").strip() or "openai/gpt-5-mini"
    temperature = _resolve_realize_temperature(difficulty)
    max_tokens = _resolve_realize_max_tokens()

    # First attempt: generate `n` drafts in one shot.
    # If the response is truncated/invalid JSON (common with LaTeX-heavy content),
    # retry in a safer "short mode" that asks for only 1 question.
    for attempt in range(2):
        target_n = n if attempt == 0 else 1
        messages = build_generation_messages(
            subject=subj,
            topic=topic,
            difficulty=difficulty,
            question_type=qtype,
            study_markdown=study_md,
            count=target_n,
            spec=spec,
            source_pack=source_pack,
        )
        if attempt > 0:
            # Force a compact retry: keep the output short and avoid meta commentary
            # that tends to bloat the response and trigger truncation.
            messages = [
                {
                    "role": "system",
                    "content": (
                        "<retry_reason>上一次 JSON 可能截断或格式有误。</retry_reason>\n"
                        "<constraints>\n"
                        "  <rule>只输出 1 道题</rule>\n"
                        "  <rule>解析 ≤ 8 句短句</rule>\n"
                        "  <rule>禁止陷阱/易错/点评等元文本</rule>\n"
                        "  <rule>禁止重复题干内容</rule>\n"
                        "  <rule>若题目条件导致无解或矛盾，直接换一道合理可解的题目</rule>\n"
                        "</constraints>\n"
                        "<output_format>仅输出 JSON object，确保完整闭合。</output_format>"
                    ),
                },
                *messages,
            ]

        text = await _chat_json_with_reasoning(
            messages=messages,
            model=model,
            temperature=temperature,
            max_tokens=max_tokens,
            req_id_prefix="qlg",
            retries=3,
            raise_on_fail=True,
            stage_id="draft_realization",
            stage_label="草稿生成",
            stream_reasoning=stream_reasoning,
            on_reasoning_event=on_reasoning_event,
        )

        qs = _extract_question_items(_extract_json_value(text))
        out: List[dict] = []
        for q in qs:
            normalized = _normalize_question_item(q, spec)
            if normalized is None:
                continue
            out.append(normalized)
            if len(out) >= n:
                break
        if out:
            return out

    return []


def build_generation_messages(
    *,
    subject: str,
    topic: str,
    difficulty: str,
    question_type: str,
    study_markdown: str,
    count: int,
    spec: Optional[dict] = None,
    source_pack: Optional[dict] = None,
) -> List[Dict[str, str]]:
    family = infer_subject_family(subject)
    bank = get_subject_bank(subject)

    def _subject_must_have_lines() -> List[str]:
        if family == "physics":
            return [
                "<physics_requirements>",
                "  <process_model>必须体现物理过程建模：明确对象/系统、受力或能量路径，并写出关键物理量关系式。</process_model>",
                "  <sign_and_units>符号方向与单位量纲必须自洽，必要时做量纲检验。</sign_and_units>",
                "  <diagram_if_needed>若题意需要示意图，需在题干中明确图像信息（坐标/方向/标注）。</diagram_if_needed>",
                "</physics_requirements>",
            ]
        if family == "chemistry":
            return [
                "<chemistry_requirements>",
                "  <equation>化学方程式/离子方程式必须配平，状态条件完整且正确。</equation>",
                "  <conservation>优先使用守恒（元素/电荷/电子）建立关系，结论可复核。</conservation>",
                "  <principle>化学原理正确，不以记忆性结论替代推理。</principle>",
                "</chemistry_requirements>",
            ]
        if family == "biology":
            return [
                "<biology_requirements>",
                "  <concept_boundary>关键概念边界清晰，避免概念混淆。</concept_boundary>",
                "  <evidence_chain>推理必须有证据链：材料信息 -> 推断 -> 结论。</evidence_chain>",
                "  <experiment>若为实验题，必须体现对照与变量控制。</experiment>",
                "</biology_requirements>",
            ]
        if family == "chinese":
            return [
                "<chinese_requirements>",
                "  <text_evidence>答案必须基于文本证据，不写空泛套话。</text_evidence>",
                "  <structure>分点作答，先结论后依据，表述规范准确。</structure>",
                "</chinese_requirements>",
            ]
        if family == "english":
            return [
                "<english_requirements>",
                "  <discourse>强调语篇理解与定位证据；避免凭感觉。</discourse>",
                "  <grammar>语法点必须正确且可解释（时态/语态/从句/非谓语）。</grammar>",
                "  <answer_style>答案简洁、规范，解析指出关键依据与推断链条。</answer_style>",
                "</english_requirements>",
            ]
        # math / generic
        return [
            "<core_requirements>",
            "  <thinking_depth>至少满足以下一项——多步推导链条(≥3步)、参数范围讨论(≥2种情况)、构造辅助对象、数形结合转化、反证/归谬论证</thinking_depth>",
            "  <discrimination>禁止直接套用单一公式，禁止教材例题换数字，必须有新约束条件或≥2个知识点交叉</discrimination>",
            "  <answer_determinacy>条件充分无矛盾，推导路径可复现，结论唯一明确</answer_determinacy>",
            "</core_requirements>",
        ]

    sp = source_pack or {}
    forbid = [str(x).strip() for x in (sp.get("forbidden_patterns") or []) if str(x or "").strip()]
    mistakes = [str(x).strip() for x in (sp.get("common_mistakes") or []) if str(x or "").strip()]
    skills = [str(x).strip() for x in (sp.get("skills") or []) if str(x or "").strip()]
    reference_patterns = [str(x).strip() for x in (sp.get("reference_patterns") or []) if str(x or "").strip()]
    difficulty_calibration = [str(x).strip() for x in (sp.get("difficulty_calibration") or []) if str(x or "").strip()]
    reference_format_conventions = [str(x).strip() for x in (sp.get("reference_format_conventions") or []) if str(x or "").strip()]
    raw_reference_examples = sp.get("reference_examples") if isinstance(sp.get("reference_examples"), list) else []
    reference_examples = []
    for item in raw_reference_examples:
        if not isinstance(item, dict):
            continue
        reference_examples.append(
            {
                "question_id": str(item.get("question_id") or "").strip(),
                "source": str(item.get("source") or "").strip(),
                "why_selected": str(item.get("why_selected") or "").strip(),
                "stem": str(item.get("stem") or "").strip(),
                "answer_style": str(item.get("answer_style") or "").strip(),
                "analysis_style": str(item.get("analysis_style") or "").strip(),
            }
        )

    payload = {
        "subject": subject,
        "topic": topic,
        "difficulty": difficulty,
        "question_type": question_type,
        "study_markdown": study_markdown,
        "count": count,
        "spec": {
            "seed_tag": str((spec or {}).get("seed_tag") or "").strip(),
            "skill": str((spec or {}).get("skill") or "").strip(),
            "reasoning": str((spec or {}).get("reasoning") or "").strip(),
            "trap": str((spec or {}).get("trap") or "").strip(),
            "surface": str((spec or {}).get("surface") or "").strip(),
            "brainstorm_concept": str((spec or {}).get("brainstorm_concept") or "").strip(),
            "brainstorm_angle": str((spec or {}).get("brainstorm_angle") or "").strip(),
            "brainstorm_scenario": str((spec or {}).get("brainstorm_scenario") or "").strip(),
            "brainstorm_novelty_note": str((spec or {}).get("brainstorm_novelty_note") or "").strip(),
            "brainstorm_skill_hint": str((spec or {}).get("brainstorm_skill_hint") or "").strip(),
            "brainstorm_reasoning_hint": str((spec or {}).get("brainstorm_reasoning_hint") or "").strip(),
        },
        "quality_hints": {
            "preferred_skills": skills[:10],
            "common_mistakes": mistakes[:10],
            "forbidden_patterns": forbid[:12],
            "reference_patterns": reference_patterns[:8],
            "difficulty_calibration": difficulty_calibration[:6],
            "format_conventions": reference_format_conventions[:6],
            "length_budget": {
                # Hard-ish caps to keep JSON responses small enough to be reliably
                # parseable (avoid max_tokens truncation), especially on verbose models.
                "max_sub_questions": 2,
                "stem_max_chars": 520,
                "answer_max_chars": 600,
                "analysis_max_chars": 1500,
            },
            "must_have": [
                *_subject_must_have_lines(),
                "<format_standards>",
                "  <latex_compliance>行内\\(...\\)、独立\\[...\\]，严禁$...$/$$$...$$$；"
                "分数用\\frac{}{}，根号用\\sqrt{}，上下标必须加花括号；"
                "三角函数用\\sin/\\cos/\\tan，对数用\\ln/\\lg/\\log_{}；"
                "向量用\\vec{}或\\overrightarrow{}，希腊字母用LaTeX命令禁用Unicode；"
                "表格/矩阵/分段函数用array/matrix/cases环境</latex_compliance>",
                "  <analysis_completeness>关键步骤必须展示推导过程，每步有定理/公式依据，"
                "不允许'显然''易知'等跳步表述，逻辑链条连贯</analysis_completeness>",
                "  <stem_conciseness>条件表述无冗余无歧义，信息密度高，阅读负担小</stem_conciseness>",
                "</format_standards>",
                "<quality_control>",
                "  <difficulty_calibration>严格匹配指定难度等级，计算量与思维量平衡</difficulty_calibration>",
                "  <knowledge_boundary>紧扣指定知识点范围，不超纲不偏题</knowledge_boundary>",
                "  <computation_control>数值运算步骤适中(≤8步基本运算)，避免繁琐无意义计算</computation_control>",
                "  <context_authenticity>若含应用背景，数据需符合常识，逻辑自洽</context_authenticity>",
                "  <answer_complete>answer字段必须给出完整最终结果，禁止'略'/'见解析'；"
                "analysis结论必须与answer逐符号一致</answer_complete>",
                "  <tool_verify>涉及数值计算/方程求解/不等式验证时，必须调用python_scientific_compute工具验算</tool_verify>",
                "</quality_control>",
            ],
        },
        "reference_examples": reference_examples[:3],
        "output_schema": {
            "questions": [
                {
                    "stem": "string",
                    "answer": "string",
                    "analysis": "string",
                }
            ]
        },
    }

    system_content = (
        f"<role>{str(bank.system_role or '').strip() or '你是资深高中教研员，兼具出题、解题与审题三重视角。'}</role>\n"
        "<output_format>严格输出 JSON object，禁止 Markdown 代码块或任何解释文字。</output_format>\n"
        "\n"
        "<!-- ═══════ 公式格式强制规范 ═══════ -->\n"
        "<latex_rules>\n"
        "  <delimiter>\n"
        "    行内公式：\\(...\\)　独立公式：\\[...\\]\n"
        "    严禁 $...$、$$...$$、\\begin{equation}、\\begin{align} 等一切其他定界符\n"
        "  </delimiter>\n"
        "  <standard_notation>\n"
        "    分数：\\frac{a}{b}　　根号：\\sqrt{n}、\\sqrt[3]{x}\n"
        "    上下标：x^{2}、a_{n}（单字符也必须加花括号）\n"
        "    向量：\\vec{a}、\\overrightarrow{AB}\n"
        "    极限：\\lim_{n \\to \\infty}　求和：\\sum_{i=1}^{n}　积分：\\int_{a}^{b}\n"
        "    希腊字母：\\alpha、\\beta、\\theta、\\lambda、\\pi 等，禁止 Unicode 希腊字符\n"
        "    集合：\\in、\\subset、\\subseteq、\\cup、\\cap、\\emptyset、\\mathbb{R}\n"
        "    逻辑：\\Rightarrow、\\Leftrightarrow、\\forall、\\exists、\\neg\n"
        "    组合数/排列数：\\binom{n}{k} 或 C_{n}^{k}、A_{n}^{k}\n"
        "    绝对值/范数：|x| 或 \\lvert x \\rvert\n"
        "    三角函数：\\sin、\\cos、\\tan、\\cot（反斜杠开头，禁止直接写 sin x）\n"
        "    对数：\\ln、\\lg、\\log_{a}\n"
        "  </standard_notation>\n"
        "  <structure>\n"
        "    表格/矩阵/分布列/分类讨论：必须用 LaTeX array/matrix/cases 环境，禁止纯文本竖排\n"
        "    分段函数/条件：必须用 cases 环境\n"
        "    多行推导不要拆成多个独立公式块，应在单个 aligned 或 array 中完成\n"
        "  </structure>\n"
        "  <integrity>\n"
        "    所有花括号、圆括号、方括号必须完整配对闭合\n"
        "    嵌套公式层次清晰，避免歧义\n"
        "    禁止图片公式、MathML、SVG\n"
        "    题干/答案/解析三个字段统一遵守上述全部规范\n"
        "  </integrity>\n"
        "</latex_rules>\n"
        "\n"
        "<!-- ═══════ 难度控制 ═══════ -->\n"
        f"<difficulty>{_difficulty_instruction(difficulty)}</difficulty>\n"
        "\n"
        "<!-- ═══════ 出题创意与区分度 ═══════ -->\n"
        "<creativity_standards>\n"
        "  <anti_template>严禁\u201c教材例题换数字\u201d式出题；每道题必须至少包含一个原创设计点：\n"
        "    新约束条件 / 跨知识点交叉 / 非常规设问角度 / 真实情境迁移 / 开放性探究。</anti_template>\n"
        "  <scenario_design>若引入应用情境，情境必须服务于数学/学科建模，而非纯粹背景装饰；\n"
        "    数据符合常识、逻辑自洽、可在题内完成验证。</scenario_design>\n"
        "  <thinking_depth>每道题需要可复现的推理链条（避免纯记忆/纯套公式），\n"
        "    至少满足一项：多步推导(≥3步) / 参数讨论(≥2情况) / 构造辅助对象 / 数形结合 / 反证归谬。</thinking_depth>\n"
        "  <discrimination>具备区分度：中等生与优秀生在该题上应呈现不同的解题路径或完成度。</discrimination>\n"
        "  <length_limit>最多2小问；解析只写关键推导步骤，禁止输出陷阱提示、易错点评等元文本。</length_limit>\n"
        "</creativity_standards>\n"
        "<brainstorm_guidance>\n"
        "  若 spec 中包含 brainstorm_concept / brainstorm_angle / brainstorm_scenario：\n"
        "    必须在题干约束或设问顺序中体现该创意上下文；\n"
        "    创意落地为可解的条件与结论，严禁堆砌背景故事。\n"
        "  若 brainstorm_novelty_note 有内容：将其作为\u201c题目独特性\u201d的硬约束，不是建议。\n"
        "</brainstorm_guidance>\n"
        "\n"
        "<!-- ═══════ 科学计算工具（MCP）使用指导 ═══════ -->\n"
        "<tool_usage_policy>\n"
        "  你拥有 python_scientific_compute 工具（Python 沙盒：math/cmath/numpy/sympy 等）。\n"
        "  <when_to_call>以下任一情况必须调用工具验算，不可仅靠心算：\n"
        "    1. 涉及具体数值计算（方程求解、极值、定积分、排列组合数、概率值等）\n"
        "    2. 需要验证不等式/恒等式是否成立\n"
        "    3. 需要求解含参方程、判别式、临界值\n"
        "    4. 题目涉及数列求和、递推关系验证\n"
        "    5. 需要确认答案的数值正确性\n"
        "    6. 任何你对计算结果不够确信的场景\n"
        "  </when_to_call>\n"
        "  <how_to_call>先生成题目草稿，然后调用工具验算关键步骤；\n"
        "    若工具结果与手算不一致，以工具结果为准并修正题目/答案。\n"
        "    一次生成过程中允许多次调用工具。</how_to_call>\n"
        "  <benefit>使用工具验算可极大提升答案正确率，请积极主动使用。</benefit>\n"
        "</tool_usage_policy>\n"
        "\n"
        "<!-- ═══════ 试题与答案严格性 ═══════ -->\n"
        "<answer_strictness>\n"
        "  <completeness>answer 字段必须给出完整最终结果，不允许\u201c略\u201d、\u201c见解析\u201d、省略号等。\n"
        "    选择题给出选项字母；填空题给出精确值/表达式；解答题给出最终结论。</completeness>\n"
        "  <determinacy>题干条件必须充分且无矛盾，保证解唯一确定（除非题型要求开放探究）。\n"
        "    不允许出现\u201c答案不唯一\u201d\u201c条件不足\u201d的情况。</determinacy>\n"
        "  <consistency>analysis 中的推导结论必须与 answer 字段完全一致，逐字/逐符号对齐。</consistency>\n"
        "  <precision>数值结果保留题目要求的精度；无特殊要求时，保留到最简分数或根式。\n"
        "    禁止出现近似值替代精确值的情况（除非题目明确要求近似）。</precision>\n"
        "</answer_strictness>\n"
        "<analysis_strictness>\n"
        "  <rigor>每一步推导必须有依据（定理/公式/已知条件），不允许\u201c显然\u201d\u201c易知\u201d等跳步表述。</rigor>\n"
        "  <key_steps>关键变换（换元、放缩、构造、分类）必须写明理由和合法性。</key_steps>\n"
        "  <no_meta>禁止输出\"本题考查了...\"\"易错点是...\"\"解题技巧是...\"等元评论文本。</no_meta>\n"
        "</analysis_strictness>\n"
        "\n"
        "<!-- ═══════ 自检流程（生成后必须执行） ═══════ -->\n"
        "<verification_process>\n"
        "  <step id='1'>从头独立解题，逐步验证每一步推导的正确性（建议调用 python_scientific_compute 验算）</step>\n"
        "  <step id='2'>检查题干条件：无矛盾、无冗余、信息充分、解唯一</step>\n"
        "  <step id='3'>逐字核对 answer 字段与 analysis 末尾结论完全一致</step>\n"
        "  <step id='4'>检查所有公式是否符合 latex_rules 规范（定界符、花括号、标准写法）</step>\n"
        "  <step id='5'>检查 JSON 结构完整闭合，字符串内无未转义的特殊字符</step>\n"
        "  <on_error>验算发现错误则修正后输出；题目无解/矛盾/过繁则直接换题，不要强行修补。</on_error>\n"
        "</verification_process>\n"
        "\n"
        "<reference_learning>\n"
        "  若 reference_examples/reference_patterns 有内容：学习其设问结构、解析格式与难度分布。\n"
        "  严禁照抄原题原数值原结论；只借鉴\u201c出题方式\u201d，不复制\u201c题目内容\u201d。\n"
        "</reference_learning>\n"
        "<json_integrity>确保 JSON 完整闭合可解析，不输出任何截断内容。</json_integrity>"
    )

    return [
        {"role": "system", "content": system_content},
        {"role": "user", "content": json.dumps(payload, ensure_ascii=False)},
    ]


def build_regenerate_section_messages(
    *,
    subject: str,
    topic: str,
    difficulty: str,
    question_type: str,
    study_markdown: str,
    section_key: str,
    stem: str,
    answer: str,
    analysis: str,
) -> List[Dict[str, str]]:
    normalized_key = str(section_key or "").strip() or "analysis"
    if normalized_key not in {"stem", "answer", "analysis"}:
        normalized_key = "analysis"

    payload = {
        "subject": subject,
        "topic": topic,
        "difficulty": difficulty,
        "question_type": question_type,
        "study_markdown": study_markdown,
        "section_key": normalized_key,
        "current_question": {
            "stem": stem,
            "answer": answer,
            "analysis": analysis,
        },
        "output_schema": {
            "section_key": normalized_key,
            "content": "string",
        },
    }

    system_content = (
        "<role>你是资深高中教研员，负责局部重写试题的指定部分（题干/答案/解析之一）。</role>\n"
        "<edit_principle>只重写 section_key 指定的字段，保持其他字段的知识点、难度与结论不变。</edit_principle>\n"
        "\n"
        "<latex_rules><!-- LaTeX 公式格式强制规范 -->\n"
        "  <delimiter>行内公式：\\(...\\)　独立公式：\\[...\\]　严禁 $...$、$$...$$、\\begin{equation}、\\begin{align} 等</delimiter>\n"
        "  <standard_notation>\n"
        "    分数：\\frac{a}{b}　根号：\\sqrt{n}、\\sqrt[3]{x}　上下标：x^{2}、a_{n}（单字符也必须加花括号）\n"
        "    向量：\\vec{a}、\\overrightarrow{AB}　极限：\\lim_{n \\to \\infty}　求和：\\sum_{i=1}^{n}　积分：\\int_{a}^{b}\n"
        "    希腊字母：\\alpha、\\beta、\\theta、\\lambda、\\pi 等，禁止 Unicode 希腊字符\n"
        "    集合：\\in、\\subset、\\subseteq、\\cup、\\cap、\\emptyset、\\mathbb{R}\n"
        "    逻辑：\\Rightarrow、\\Leftrightarrow、\\forall、\\exists、\\neg\n"
        "    三角函数：\\sin、\\cos、\\tan、\\cot（反斜杠开头）　对数：\\ln、\\lg、\\log_{a}\n"
        "    组合数/排列数：\\binom{n}{k} 或 C_{n}^{k}、A_{n}^{k}\n"
        "  </standard_notation>\n"
        "  <structure>表格/矩阵/分段函数/分类讨论：必须用 array/matrix/cases 环境，禁止纯文本竖排；多行推导用 aligned 环境</structure>\n"
        "  <integrity>所有花括号、圆括号、方括号必须完整配对闭合；禁止图片公式、MathML、SVG</integrity>\n"
        "</latex_rules>\n"
        "\n"
        "<answer_strictness>\n"
        "  answer 字段必须给出完整最终结果，禁止『略』『见解析』等；analysis 结论必须与 answer 逐符号一致。\n"
        "  每步推导须有定理/公式依据，不允许『显然』『易知』等跳步表述。\n"
        "</answer_strictness>\n"
        "<tool_usage>若重写涉及数值计算/方程求解，请调用 python_scientific_compute 工具验算后再输出。</tool_usage>\n"
        "<verification>重写后验算答案正确性，确保推导无误、结论与其余部分完全一致。</verification>\n"
        "<output_format>严格输出 JSON object，不输出 Markdown 或解释。</output_format>"
    )

    return [
        {"role": "system", "content": system_content},
        {"role": "user", "content": json.dumps(payload, ensure_ascii=False)},
    ]


async def regenerate_question_section(
    *,
    subject: str,
    topic: str,
    difficulty: str,
    question_type: str,
    study_markdown: str,
    section_key: str,
    stem: str,
    answer: str,
    analysis: str,
) -> str:
    if not is_llm_configured():
        return ""

    messages = build_regenerate_section_messages(
        subject=subject,
        topic=topic,
        difficulty=difficulty,
        question_type=question_type,
        study_markdown=study_markdown,
        section_key=section_key,
        stem=stem,
        answer=answer,
        analysis=analysis,
    )

    text = await _chat_json_with_reasoning(
        messages=messages,
        model=str(LESSON_PLAN_MODEL or "").strip() or "openai/gpt-5-mini",
        temperature=float(LESSON_PLAN_TEMPERATURE),
        max_tokens=0,
        req_id_prefix="qlr",
        retries=3,
        raise_on_fail=False,
        stage_id="draft_realization",
        stage_label="草稿生成",
        stream_reasoning=False,
        on_reasoning_event=None,
    )

    obj = _extract_json_obj(text)
    content = str(obj.get("content") or "").strip()
    if content:
        return content

    fallback_key = str(section_key or "").strip()
    if fallback_key in {"stem", "answer", "analysis"}:
        return str(obj.get(fallback_key) or "").strip()
    return ""
