from __future__ import annotations

import json
import os
from typing import Any, Dict, List, Optional

from backend.core.logging_utils import get_logger
from backend.core.settings import LESSON_PLAN_MAX_TOKENS, LESSON_PLAN_MODEL, LESSON_PLAN_TEMPERATURE
from backend.generation.question_library.curriculum_context import curriculum_context_for_prompt
from backend.generation.question_library.gen_common import (
    DEFAULT_SEARCH_CONFIG,
    _difficulty_instruction,
    _resolve_realize_temperature,
)
from backend.generation.question_library.gen_llm import (
    _chat_json_with_reasoning,
    _extract_json_obj,
    _extract_json_value,
)
from backend.generation.question_library.gen_utils import ReasoningEventHandler
from backend.generation.question_library.intuition_practice import (
    normalize_intuition_atom,
    normalize_intuition_packet,
    normalize_intuition_practice_config,
)
from backend.generation.question_library.subject_knowledge import get_subject_bank, infer_subject_family
from backend.llm.client import is_llm_configured
from backend.llm.prompts import create_default_prompt_registry

logger = get_logger(__name__)
_realize_max_tokens_invalid_logged = False


def _prompt(prompt_id: str) -> str:
    return create_default_prompt_registry().render(prompt_id).content


def _resolve_realize_max_tokens() -> int:
    raw = str(os.getenv("QUESTION_LIBRARY_REALIZE_MAX_TOKENS") or "").strip()
    if raw:
        try:
            return max(1, int(raw))
        except Exception:
            global _realize_max_tokens_invalid_logged
            if not _realize_max_tokens_invalid_logged:
                _realize_max_tokens_invalid_logged = True
                logger.warning(
                    "question_library_realize_max_tokens_invalid",
                    extra={"value": raw},
                    exc_info=True,
                )
    try:
        base = int(LESSON_PLAN_MAX_TOKENS or 0)
    except (TypeError, ValueError):
        base = 0
    min_budget = int(DEFAULT_SEARCH_CONFIG.get("realize_min_max_tokens") or 5000)
    return max(base, min_budget)


def _normalize_question_text(value: Any) -> str:
    if isinstance(value, list):
        parts = [str(item or "").strip() for item in value if str(item or "").strip()]
        return "\n".join(parts).strip()
    return str(value or "").strip()


def _extract_question_items(payload: Any) -> List[dict]:
    if isinstance(payload, list):
        return [item for item in payload if isinstance(item, dict)]
    if not isinstance(payload, dict):
        return []

    for key in ("questions", "题目", "试题"):
        items = payload.get(key)
        if isinstance(items, list):
            return [item for item in items if isinstance(item, dict)]

    if any(key in payload for key in ("stem", "题干", "question", "answer", "答案", "analysis", "解析")):
        return [payload]
    return []


def _normalize_question_item(q: dict, spec: dict) -> Optional[dict]:
    if not isinstance(q, dict):
        return None

    stem = _normalize_question_text(q.get("stem") or q.get("题干") or q.get("question") or q.get("题目"))
    ans = _normalize_question_text(q.get("answer") or q.get("答案") or q.get("参考答案"))
    ana = _normalize_question_text(q.get("analysis") or q.get("解析") or q.get("解答"))
    if not stem or not ans or not ana:
        return None

    diagrams = q.get("diagrams")
    normalized_diagrams = diagrams if isinstance(diagrams, list) else None
    practice_config = normalize_intuition_practice_config((spec or {}).get("intuition_practice"))
    atom = normalize_intuition_atom(
        q.get("intuition_atom") or (spec or {}).get("intuition_atom"),
        subject=str((spec or {}).get("subject") or ""),
        topic=str((spec or {}).get("topic") or ""),
        seed_tag=str((spec or {}).get("seed_tag") or ""),
    )
    intuition_packet = normalize_intuition_packet(
        q.get("intuition_packet"),
        practice_config=practice_config,
        atom=atom,
        subject=str((spec or {}).get("subject") or ""),
        topic=str((spec or {}).get("topic") or ""),
        seed_tag=str((spec or {}).get("seed_tag") or ""),
        legacy_question={"stem": stem, "answer": ans, "analysis": ana},
    )

    out = {
        "stem": stem,
        "answer": ans,
        "analysis": ana,
        "spec_id": str((spec or {}).get("spec_id") or "").strip(),
        "skill": str((spec or {}).get("skill") or "").strip(),
        "reasoning": str((spec or {}).get("reasoning") or "").strip(),
        "trap": str((spec or {}).get("trap") or "").strip(),
        "surface": str((spec or {}).get("surface") or "").strip(),
        "seed_tag": str((spec or {}).get("seed_tag") or "").strip(),
        "intuition_packet": intuition_packet,
        "intuition_score": float((spec or {}).get("intuition_alignment") or 0.0),
    }

    # Keep diagram payload when present (generated by diagram stage).
    if normalized_diagrams is not None:
        out["diagrams"] = [d for d in normalized_diagrams if isinstance(d, dict)][:6]

    return out


async def realize_drafts(
    spec: dict,
    *,
    source_pack: dict,
    n: int = 2,
    stream_reasoning: bool = False,
    on_reasoning_event: ReasoningEventHandler = None,
) -> List[dict]:
    if not is_llm_configured():
        return []

    subj = str((spec or {}).get("subject") or (source_pack or {}).get("subject") or "").strip() or "高中数学"
    topic = str((spec or {}).get("topic") or (source_pack or {}).get("topic") or "").strip()
    difficulty = str((spec or {}).get("difficulty") or "").strip()
    qtype = str((spec or {}).get("question_type") or "").strip()
    study_md = str((source_pack or {}).get("study_markdown") or "").strip()
    n = max(1, min(int(n or 1), 4))

    model = str(LESSON_PLAN_MODEL or "").strip() or "openai/gpt-5-mini"
    temperature = _resolve_realize_temperature(difficulty)
    max_tokens = _resolve_realize_max_tokens()

    # First attempt: generate `n` drafts in one shot.
    # If the response is truncated/invalid JSON (common with LaTeX-heavy content),
    # retry in a safer "short mode" that asks for only 1 question.
    for attempt in range(2):
        target_n = n if attempt == 0 else 1
        messages = build_generation_messages(
            subject=subj,
            topic=topic,
            difficulty=difficulty,
            question_type=qtype,
            study_markdown=study_md,
            count=target_n,
            spec=spec,
            source_pack=source_pack,
        )
        if attempt > 0:
            # Force a compact retry: keep the output short and avoid meta commentary
            # that tends to bloat the response and trigger truncation.
            messages = [
                {
                    "role": "system",
                    "content": (
                        "<retry_reason>The previous JSON may have been truncated or malformed.</retry_reason>\n"
                        "<constraints>\n"
                        "  <rule>Output exactly one question.</rule>\n"
                        "  <rule>Keep analysis to <= 8 short sentences.</rule>\n"
                        "  <rule>Do not output meta-text such as trap hints, common mistakes, or comments.</rule>\n"
                        "  <rule>Do not repeat stem content.</rule>\n"
                        "  <rule>If the conditions make the question unsolvable or contradictory, replace it with a reasonable solvable question.</rule>\n"
                        "</constraints>\n"
                        "<output_format>Output only a JSON object and ensure it is fully closed.</output_format>"
                    ),
                },
                *messages,
            ]

        text = await _chat_json_with_reasoning(
            messages=messages,
            model=model,
            temperature=temperature,
            max_tokens=max_tokens,
            req_id_prefix="qlg",
            retries=3,
            raise_on_fail=True,
            stage_id="draft_realization",
            stage_label="练习包生成",
            stream_reasoning=stream_reasoning,
            on_reasoning_event=on_reasoning_event,
        )

        qs = _extract_question_items(_extract_json_value(text))
        out: List[dict] = []
        for q in qs:
            normalized = _normalize_question_item(q, spec)
            if normalized is None:
                continue
            out.append(normalized)
            if len(out) >= n:
                break
        if out:
            return out

    return []


def build_generation_messages(
    *,
    subject: str,
    topic: str,
    difficulty: str,
    question_type: str,
    study_markdown: str,
    count: int,
    spec: Optional[dict] = None,
    source_pack: Optional[dict] = None,
) -> List[Dict[str, str]]:
    family = infer_subject_family(subject)
    bank = get_subject_bank(subject)

    def _subject_must_have_lines() -> List[str]:
        if family == "physics":
            return [
                "<physics_requirements>",
                "  <process_model>Reflect physical-process modeling: identify the object/system, force or energy path, and key physical-quantity relationships.</process_model>",
                "  <sign_and_units>Sign directions and units/dimensions must be self-consistent; perform dimensional checks when needed.</sign_and_units>",
                "  <diagram_if_needed>If the question requires a diagram, explicitly state the image information in the stem, such as coordinates, directions, and labels.</diagram_if_needed>",
                "</physics_requirements>",
            ]
        if family == "chemistry":
            return [
                "<chemistry_requirements>",
                "  <equation>Chemical/ionic equations must be balanced, with complete and correct states and conditions.</equation>",
                "  <conservation>Prefer conservation of elements, charge, or electrons to build relationships; conclusions must be checkable.</conservation>",
                "  <principle>Chemical principles must be correct; do not replace reasoning with memorized conclusions.</principle>",
                "</chemistry_requirements>",
            ]
        if family == "biology":
            return [
                "<biology_requirements>",
                "  <concept_boundary>Key concept boundaries must be clear to avoid concept confusion.</concept_boundary>",
                "  <evidence_chain>Reasoning must include an evidence chain: material information -> inference -> conclusion.</evidence_chain>",
                "  <experiment>For experiment questions, include control groups and variable control.</experiment>",
                "</biology_requirements>",
            ]
        if family == "chinese":
            return [
                "<chinese_requirements>",
                "  <text_evidence>Answers must be based on textual evidence, not generic boilerplate.</text_evidence>",
                "  <structure>Use point-by-point answers: conclusion first, then evidence, with standard and accurate wording.</structure>",
                "</chinese_requirements>",
            ]
        if family == "english":
            return [
                "<english_requirements>",
                "  <discourse>Emphasize discourse comprehension and located evidence; avoid intuition-only answers.</discourse>",
                "  <grammar>Grammar points must be correct and explainable, such as tense, voice, clauses, or non-finite verbs.</grammar>",
                "  <answer_style>Answers should be concise and standard; analysis should identify key evidence and inference chains.</answer_style>",
                "</english_requirements>",
            ]
        # math / generic
        return [
            "<core_requirements>",
            "  <intuition_first>Allow a curriculum-accessible first prediction before full calculation. Low entry is not low thought: require the learner to discover a non-explicit relationship before a short proof.</intuition_first>",
            "  <internal_model>Make the learner manipulate a mathematical object through comparison, transformation, symmetry, invariants, estimation, limits, boundaries, or counterexamples.</internal_model>",
            "  <method_concealment>Do not state the decisive invariant, symmetry, representation switch, named formula, or complete method sequence in the stem when discovering it is the intended mathematical action.</method_concealment>",
            "  <routine_rejection>Reject a design whose central demand is only substituting given values into a displayed/named formula or carrying out a fully prescribed algorithm.</routine_rejection>",
            "  <answer_determinacy>Conditions must be sufficient and non-contradictory; the derivation path must be reproducible and the conclusion unique and clear.</answer_determinacy>",
            "</core_requirements>",
        ]

    sp = source_pack or {}
    forbid = [str(x).strip() for x in (sp.get("forbidden_patterns") or []) if str(x or "").strip()]
    mistakes = [str(x).strip() for x in (sp.get("common_mistakes") or []) if str(x or "").strip()]
    skills = [str(x).strip() for x in (sp.get("skills") or []) if str(x or "").strip()]
    reference_patterns = [str(x).strip() for x in (sp.get("reference_patterns") or []) if str(x or "").strip()]
    difficulty_calibration = [str(x).strip() for x in (sp.get("difficulty_calibration") or []) if str(x or "").strip()]
    reference_format_conventions = [str(x).strip() for x in (sp.get("reference_format_conventions") or []) if str(x or "").strip()]
    raw_reference_examples = sp.get("reference_examples") if isinstance(sp.get("reference_examples"), list) else []
    reference_examples = []
    for item in raw_reference_examples:
        if not isinstance(item, dict):
            continue
        reference_examples.append(
            {
                "question_id": str(item.get("question_id") or "").strip(),
                "source": str(item.get("source") or "").strip(),
                "why_selected": str(item.get("why_selected") or "").strip(),
                "stem": str(item.get("stem") or "").strip(),
                "answer_style": str(item.get("answer_style") or "").strip(),
                "analysis_style": str(item.get("analysis_style") or "").strip(),
            }
        )

    practice_config = normalize_intuition_practice_config(
        (spec or {}).get("intuition_practice") or sp.get("intuition_practice")
    )
    intuition_atom = normalize_intuition_atom(
        (spec or {}).get("intuition_atom"),
        subject=subject,
        topic=topic,
        seed_tag=str((spec or {}).get("seed_tag") or ""),
    )

    payload = {
        "subject": subject,
        "topic": topic,
        "difficulty": difficulty,
        "question_type": question_type,
        "study_markdown": study_markdown,
        "count": count,
        "curriculum_context": curriculum_context_for_prompt(sp),
        "intuition_practice": practice_config,
        "intuition_atom": intuition_atom,
        "spec": {
            "seed_tag": str((spec or {}).get("seed_tag") or "").strip(),
            "skill": str((spec or {}).get("skill") or "").strip(),
            "reasoning": str((spec or {}).get("reasoning") or "").strip(),
            "trap": str((spec or {}).get("trap") or "").strip(),
            "surface": str((spec or {}).get("surface") or "").strip(),
            "brainstorm_concept": str((spec or {}).get("brainstorm_concept") or "").strip(),
            "brainstorm_angle": str((spec or {}).get("brainstorm_angle") or "").strip(),
            "brainstorm_scenario": str((spec or {}).get("brainstorm_scenario") or "").strip(),
            "brainstorm_novelty_note": str((spec or {}).get("brainstorm_novelty_note") or "").strip(),
            "brainstorm_mother_question_demand": str(
                (spec or {}).get("brainstorm_mother_question_demand") or ""
            ).strip(),
            "brainstorm_topic_binding": str((spec or {}).get("brainstorm_topic_binding") or "").strip(),
            "brainstorm_skill_hint": str((spec or {}).get("brainstorm_skill_hint") or "").strip(),
            "brainstorm_reasoning_hint": str((spec or {}).get("brainstorm_reasoning_hint") or "").strip(),
            "intuition_alignment": float((spec or {}).get("intuition_alignment") or 0.0),
        },
        "quality_hints": {
            "preferred_skills": skills[:10],
            "common_mistakes": mistakes[:10],
            "forbidden_patterns": forbid[:12],
            "reference_patterns": reference_patterns[:8],
            "difficulty_calibration": difficulty_calibration[:6],
            "format_conventions": reference_format_conventions[:6],
            "length_budget": {
                # Hard-ish caps to keep JSON responses small enough to be reliably
                # parseable (avoid max_tokens truncation), especially on verbose models.
                "max_sub_questions": 2,
                "stem_max_chars": 520,
                "answer_max_chars": 600,
                "analysis_max_chars": 1500,
            },
            "must_have": [
                *_subject_must_have_lines(),
                "<format_standards>",
                "  <latex_compliance>Use inline \\(...\\) and display \\[...\\]. Do not use $...$ or $$$...$$$. "
                "Use \\frac{}{} for fractions and \\sqrt{} for radicals. Superscripts/subscripts must use braces. "
                "Use \\sin/\\cos/\\tan for trigonometric functions and \\ln/\\lg/\\log_{} for logarithms. "
                "Use \\vec{} or \\overrightarrow{} for vectors. Use LaTeX commands for Greek letters and avoid Unicode Greek letters. "
                "Use array/matrix/cases environments for tables, matrices, and piecewise functions.</latex_compliance>",
                "  <analysis_completeness>Key steps must show derivation, with theorem/formula support for each step. "
                "Avoid skipped-step wording such as 'obvious'; keep the logic chain coherent.</analysis_completeness>",
                "  <stem_conciseness>Condition wording must be non-redundant, unambiguous, information-dense, and easy to read.</stem_conciseness>",
                "</format_standards>",
                "<quality_control>",
                "  <difficulty_calibration>Strictly match the requested difficulty level and balance computation load with reasoning load.</difficulty_calibration>",
                "  <knowledge_boundary>Stay within curriculum_context.knowledge_scope.in_scope; do not use out_of_scope content.</knowledge_boundary>",
                "  <prerequisites>Assume students already know curriculum_context.prerequisites; do not re-teach them in the stem.</prerequisites>",
                "  <curriculum_alignment>Follow curriculum_context.question_requirements and core_competencies from the high-school curriculum standard.</curriculum_alignment>",
                "  <computation_control>Keep numerical computation moderate, at most 8 basic-operation steps; avoid tedious meaningless calculation.</computation_control>",
                "  <context_authenticity>If an application context is included, data must be common-sense plausible and logically self-consistent.</context_authenticity>",
                "  <answer_complete>The answer field must provide the complete final result. Do not use 'omitted' or 'see analysis'. "
                "The analysis conclusion must match answer symbol-by-symbol.</answer_complete>",
                "  <tool_verify>When numerical calculation, equation solving, or inequality verification is involved, call python_scientific_compute to verify.</tool_verify>",
                "</quality_control>",
            ],
        },
        "reference_examples": reference_examples[:3],
        "output_schema": {
            "questions": [
                {
                    "stem": "string",
                    "answer": "string",
                    "analysis": "string",
                    "intuition_packet": {
                        "version": "1.0",
                        "practice_goal": practice_config["practice_goal"],
                        "atom": intuition_atom,
                        "stages": [
                            {
                                "stage": "perception|model_externalization|minimal_check|transfer|appreciation",
                                "kind": "prediction|representation|invariant|boundary|counterexample|solution_comparison",
                                "prompt": "string",
                                "hint": "string",
                                "expected_answer": "string",
                                "feedback": "string",
                            }
                        ],
                        "curriculum_alignment": {
                            "knowledge_points": "string[]",
                            "scope_note": "string",
                        },
                    },
                }
            ]
        },
    }

    selected_goal_contract = ""
    if practice_config["practice_goal"] == "solution_appreciation":
        selected_goal_contract = (
            "  <selected_goal_contract>For this selected goal, the stem itself MUST contain a scored demand that asks "
            "the learner to find or construct two genuinely different routes/representations, compare them under one "
            "or more explicit structural criteria, and justify the comparison using steps from this problem. The stem "
            "must not name the intended routes or preferred winner. This is not forbidden method leakage: the learner, "
            "not the stem, supplies the routes. Before that comparison, the core object must independently require the "
            "requested hidden symmetry, invariant, relation, boundary, or representation insight. If either requirement "
            "is absent, do not output the draft.</selected_goal_contract>\n"
        )

    system_content = (
        _prompt("question.draft.realize.v1")
        + "\n\n"
        f"<role>{str(bank.system_role or '').strip() or 'You are a senior high-school curriculum researcher with question-writing, solving, and reviewing perspectives.'}</role>\n"
        "<language_policy>Match the user's requested language or the subject material language for question content unless explicitly instructed otherwise. Keep JSON field names and required enum values unchanged.</language_policy>\n"
        "<output_format>Output a strict JSON object only. Do not output Markdown code fences or any explanatory text.</output_format>\n"
        "\n"
        "<!-- Formula-format mandatory rules -->\n"
        "<latex_rules>\n"
        "  <delimiter>\n"
        "    Inline formulas: \\(...\\). Display formulas: \\[...\\].\n"
        "    Do not use $...$, $$...$$, \\begin{equation}, \\begin{align}, or any other delimiters.\n"
        "  </delimiter>\n"
        "  <standard_notation>\n"
        "    Fractions: \\frac{a}{b}. Radicals: \\sqrt{n}, \\sqrt[3]{x}.\n"
        "    Superscripts/subscripts: x^{2}, a_{n}; even single characters must use braces.\n"
        "    Vectors: \\vec{a}, \\overrightarrow{AB}.\n"
        "    Limits: \\lim_{n \\to \\infty}. Sums: \\sum_{i=1}^{n}. Integrals: \\int_{a}^{b}.\n"
        "    Greek letters: \\alpha, \\beta, \\theta, \\lambda, \\pi, etc. Do not use Unicode Greek letters.\n"
        "    Sets: \\in, \\subset, \\subseteq, \\cup, \\cap, \\emptyset, \\mathbb{R}.\n"
        "    Logic: \\Rightarrow, \\Leftrightarrow, \\forall, \\exists, \\neg.\n"
        "    Combinations/permutations: \\binom{n}{k} or C_{n}^{k}, A_{n}^{k}.\n"
        "    Absolute value/norm: |x| or \\lvert x \\rvert.\n"
        "    Trigonometric functions: \\sin, \\cos, \\tan, \\cot. Use a leading backslash; do not write bare sin x.\n"
        "    Logarithms: \\ln, \\lg, \\log_{a}.\n"
        "  </standard_notation>\n"
        "  <structure>\n"
        "    Tables/matrices/distribution tables/case analysis must use LaTeX array/matrix/cases environments. Do not use plain-text vertical layouts.\n"
        "    Piecewise functions/conditions must use a cases environment.\n"
        "    Multi-line derivations should not be split into multiple display blocks; use a single aligned or array environment.\n"
        "  </structure>\n"
        "  <integrity>\n"
        "    All braces, parentheses, and brackets must be fully paired and closed.\n"
        "    Nested formula structure must be clear and unambiguous.\n"
        "    Do not use image formulas, MathML, or SVG.\n"
        "    The stem, answer, and analysis fields must all follow the rules above.\n"
        "  </integrity>\n"
        "</latex_rules>\n"
        "\n"
        "<!-- Difficulty control -->\n"
        f"<difficulty>{_difficulty_instruction(difficulty)}</difficulty>\n"
        "\n"
        "<!-- Intuition calibration packet -->\n"
        "<intuition_training>\n"
        "  <definition>Intuition is a trainable internal representation: predict, expose what is mentally seen, receive a short logical correction signal, then transfer. It is not fast guessing.</definition>\n"
        "  <atom>Use intuition_atom as the single design kernel. The decisive cue must actually determine the conclusion and must match the stem and every practice stage; do not attach an unrelated or decorative atom to a routine exercise.</atom>\n"
        "  <mother_question_contract>The mother question in stem must independently force the selected mental action before any practice-stage prompt is shown.\n"
        "    Apply this removal test: if intuition_packet is deleted, a student must still need to infer a hidden relationship, reorganize a representation, detect an invariant or boundary,\n"
        "    construct/test a counterexample, or compare genuinely different routes to answer the scored demand. The packet may unpack that thinking; it must never supply all the thinking missing from a routine mother question.</mother_question_contract>\n"
        "  <requested_topic_contract>Parse the requested topic into substantive clauses and satisfy every clause in the mother question's conditions and scored demand.\n"
        "    A clause is not satisfied by copying its keyword into intuition_packet, a hint, feedback, analysis, or an appreciation comparison. For example, when topic requests symmetry and invariants,\n"
        "    solving the stem must necessarily discover/use both; a generic extremum calculation followed by a comment about symmetry is off-topic.</requested_topic_contract>\n"
        "  <low_floor_high_thought>Accessible prerequisites and a short formal check are desirable, but the learner must still infer a hidden relationship, reorganize a representation, detect an invariant/boundary, or test a counterexample.\n"
        "    Do not equate self-practice with one-step formula substitution, routine arithmetic, or following an already supplied recipe.</low_floor_high_thought>\n"
        "  <do_not_leak>decisive_cue, formal_anchor, answer, and full solution route are private authoring information.\n"
        "    The stem and perception prompt may provide sufficient evidence, but must not name or paraphrase the exact invariant, symmetry, key pairing, representation switch, boundary mechanism, formula, or complete sequence the learner is meant to discover.\n"
        "    Do not write instructions such as 'use formula X', 'use method A and method B', or an ordered list that performs the intended insight for the learner.</do_not_leak>\n"
        f"  <practice_goal selected=\"{practice_config['practice_goal']}\">\n"
        "    <fluency>Build quick facility with basic objects, mental operations, and representations, but never reward memorized template matching.</fluency>\n"
        "    <structural_intuition>Make relationships, transformations, and invariants carry the conclusion.</structural_intuition>\n"
        "    <intuition_correction>Create a safe cognitive conflict, then use a counterexample or boundary case to locate and repair the false intuition.</intuition_correction>\n"
        "    <transfer>Preserve one decisive structure while changing the surface representation and context.</transfer>\n"
        "    <solution_appreciation>Compare correct approaches and make the learner articulate why one is more natural under explicit structural criteria.</solution_appreciation>\n"
        "  </practice_goal>\n"
        + selected_goal_contract
        + f"  <feedback_mode selected=\"{practice_config['feedback_mode']}\">\n"
        "    <guided>Give progressive hints; the first hint must not reveal the final answer or decisive step.</guided>\n"
        "    <concise>Give only the decisive cue followed by a short calibration statement.</concise>\n"
        "    <reflective>Use follow-up questions that make the learner restate and revise the internal model; a reference answer may still be shown after submission.</reflective>\n"
        "  </feedback_mode>\n"
        f"  <packet_size>Output exactly {practice_config['packet_size']} stage objects.</packet_size>\n"
        "  <required_stages>The stages list must include perception, model_externalization, and transfer in that order.\n"
        "    perception asks for a first prediction before full work without leaking the decisive cue; model_externalization asks the learner to articulate the hidden object/relationship and give the shortest convincing check;\n"
        "    transfer preserves the target mental action but must alter at least one relationship, constraint direction, boundary regime, or representation. Changing only numbers, labels, or story context is invalid.</required_stages>\n"
        "  <optional_stages>When packet_size is 4 or 5, add minimal_check and/or appreciation according to practice_goal and intuition_kinds.\n"
        "    For mathematics, appreciation must compare two genuinely different correct representations or reasoning routes (for example algebraic/geometric, local/global, constructive/invariant-based)\n"
        "    using explicit criteria: simplicity, symmetry, unification, invariants, generalizability, and necessity of conditions. Cosmetic rewrites of the same formula, or formula substitution versus the same substitution written longer, do not count.\n"
        "    Ask which approach is more natural and why without announcing the preferred conclusion in the question. For other subjects use evidential economy, model explanatory power, and structural consistency.</optional_stages>\n"
        "  <appreciation_gate>Generate appreciation only after the base mother question passes the removal test and topic contract. Method comparison is an analysis lens, not a source of difficulty.\n"
        "    It cannot upgrade a routine stem. At medium difficulty, explicitly reject a stem equivalent to 'given \\(a_{n}\\), find the extremum of \\(S_{n}\\), then compare a quadratic method and a sign method',\n"
        "    unless the scored question independently forces discovery/use of every requested structural clause such as symmetry or an invariant.</appreciation_gate>\n"
        "  <feedback>Feedback must identify what the first feeling captured, where it drifted, and the decisive structure to reuse. Never shame a wrong first guess.</feedback>\n"
        "  <anti_template>Do not create a textbook example with different numbers. Reject direct formula substitution, a fully specified method route, number-only transfer, and comparisons of cosmetically identical methods.</anti_template>\n"
        "  <subpart_rule>For a multi-part stem, every subpart must preserve or deepen the same hidden structural demand.\n"
        "    Reject standard scaffolds such as '(1) find the parameters/general term; (2) use it to find a sum/extremum' when part (1) is only routine algebra and part (2) becomes formula substitution.\n"
        "    A preliminary subpart is allowed only when it asks the learner to conjecture a relationship, produce/select a representation, test a boundary, or justify an invariant—and it must not name the intended method.</subpart_rule>\n"
        "  <self_practice>Keep the entry point accessible and the formal check short. Do not force advanced proof machinery, long calculation, or artificial competition-level complexity.\n"
        "    Short is allowed; intellectually pre-solved is not.</self_practice>\n"
        "  <compatibility>stem, answer, and analysis must remain a self-contained consolidated rendering of the same packet for existing clients. They must not contradict any stage.</compatibility>\n"
        "</intuition_training>\n"
        "<brainstorm_guidance>\n"
        "  If spec contains brainstorm_concept, brainstorm_angle, or brainstorm_scenario:\n"
        "    The creative context must appear in stem constraints or the order of sub-questions.\n"
        "    Turn the idea into solvable conditions and conclusions. Do not pile up background story.\n"
        "  If brainstorm_mother_question_demand is present, realize it as a scored demand in stem itself, not merely as an intuition_packet prompt or an analysis comment.\n"
        "  If brainstorm_topic_binding is present, treat every mapping in it as mandatory and check it against the requested topic before output.\n"
        "  If brainstorm_novelty_note is present, treat it as a hard requirement for question uniqueness, not a suggestion.\n"
        "</brainstorm_guidance>\n"
        "\n"
        "<!-- Scientific computation tool (MCP) usage guidance -->\n"
        "<tool_usage_policy>\n"
        "  You have access to python_scientific_compute, a Python sandbox with math/cmath/numpy/sympy and related tools.\n"
        "  <when_to_call>Call the tool to verify in any of the following cases; do not rely only on mental arithmetic:\n"
        "    1. Specific numerical computation, such as equation solving, extrema, definite integrals, combinatorics counts, or probabilities.\n"
        "    2. Verifying whether an inequality or identity holds.\n"
        "    3. Solving parameterized equations, discriminants, or critical values.\n"
        "    4. Sequence summation or recurrence verification.\n"
        "    5. Confirming answer numerical correctness.\n"
        "    6. Any situation where you are not fully confident in the calculation result.\n"
        "  </when_to_call>\n"
        "  <how_to_call>First generate a question draft, then call the tool to verify key steps.\n"
        "    If the tool result conflicts with manual calculation, trust the tool and fix the question/answer.\n"
        "    Multiple tool calls are allowed during one generation.</how_to_call>\n"
        "  <benefit>Tool verification significantly improves answer accuracy. Use it proactively.</benefit>\n"
        "</tool_usage_policy>\n"
        "\n"
        "<!-- Question and answer strictness -->\n"
        "<answer_strictness>\n"
        "  <completeness>The answer field must provide the complete final result. Do not use omissions such as 'omitted', 'see analysis', or ellipses.\n"
        "    Multiple-choice questions must give the option letter; fill-in questions must give the exact value/expression; solution questions must give the final conclusion.</completeness>\n"
        "  <determinacy>The stem conditions must be sufficient and non-contradictory, ensuring a unique solution unless the question type requires open exploration.\n"
        "    Do not create cases where the answer is non-unique or conditions are insufficient.</determinacy>\n"
        "  <consistency>The derivation conclusion in analysis must exactly match the answer field word-by-word and symbol-by-symbol.</consistency>\n"
        "  <precision>Numerical results must follow the required precision. If unspecified, keep the simplest fraction or radical form.\n"
        "    Do not replace exact values with approximations unless the question explicitly asks for approximation.</precision>\n"
        "</answer_strictness>\n"
        "<analysis_strictness>\n"
        "  <rigor>Every derivation step must have support from a theorem, formula, or given condition. Avoid skipped-step wording such as 'obvious'.</rigor>\n"
        "  <key_steps>For key transformations such as substitution, bounding, construction, or classification, state the reason and legality.</key_steps>\n"
        "  <no_meta>Do not output meta-comments such as 'this question tests...', 'the common mistake is...', or 'the solving technique is...'.</no_meta>\n"
        "</analysis_strictness>\n"
        "\n"
        "<!-- Self-check process required after generation -->\n"
        "<verification_process>\n"
        "  <step id='1'>Solve each packet stage and verify the decisive step. Prefer calling python_scientific_compute only when numerical or symbolic verification is useful.</step>\n"
        "  <step id='2'>Check stem conditions: no contradictions, no redundancy, sufficient information, and unique solution.</step>\n"
        "  <step id='3'>Check word-by-word that the answer field exactly matches the final conclusion of analysis.</step>\n"
        "  <step id='4'>Check all formulas against latex_rules, including delimiters, braces, and standard notation.</step>\n"
        "  <step id='5'>Check that the JSON structure is fully closed and strings contain no unescaped special characters.</step>\n"
        "  <step id='6'>Delete intuition_packet mentally and check the mother question alone: it still forces the target observation/invariant/representation/boundary/counterexample/comparison; no preliminary subpart merely computes parameters or a general formula for later substitution.</step>\n"
        "  <step id='7'>Check structural depth: the stem does not reveal the decisive cue or prescribe the complete method; transfer changes a relationship/boundary/representation; appreciation routes are genuinely distinct.</step>\n"
        "  <step id='8'>Check every substantive requested-topic clause is necessary to solve a scored mother-question demand; reject method comparison bolted onto an otherwise routine task.</step>\n"
        "  <on_error>If verification finds an error, fix it before output. If the question is unsolvable, contradictory, or too complex, replace it instead of forcing a repair.</on_error>\n"
        "</verification_process>\n"
        "\n"
        "<reference_learning>\n"
        "  If reference_examples/reference_patterns are present, learn their question structure, analysis format, and difficulty distribution.\n"
        "  Do not copy the original question, values, or conclusions. Borrow only the question-writing method, not the question content.\n"
        "</reference_learning>\n"
        "<json_integrity>Ensure the JSON is complete, closed, and parseable. Do not output truncated content.</json_integrity>"
    )

    return [
        {"role": "system", "content": system_content},
        {"role": "user", "content": json.dumps(payload, ensure_ascii=False)},
    ]


def build_regenerate_section_messages(
    *,
    subject: str,
    topic: str,
    difficulty: str,
    question_type: str,
    study_markdown: str,
    section_key: str,
    stem: str,
    answer: str,
    analysis: str,
) -> List[Dict[str, str]]:
    normalized_key = str(section_key or "").strip() or "analysis"
    if normalized_key not in {"stem", "answer", "analysis"}:
        normalized_key = "analysis"

    payload = {
        "subject": subject,
        "topic": topic,
        "difficulty": difficulty,
        "question_type": question_type,
        "study_markdown": study_markdown,
        "section_key": normalized_key,
        "current_question": {
            "stem": stem,
            "answer": answer,
            "analysis": analysis,
        },
        "output_schema": {
            "section_key": normalized_key,
            "content": "string",
        },
    }

    system_content = (
        _prompt("question.section.regenerate.v1")
        + "\n\n"
        "<role>You are a senior high-school curriculum researcher responsible for locally rewriting one specified question section: stem, answer, or analysis.</role>\n"
        "<edit_principle>Rewrite only the field specified by section_key. Keep the other fields' knowledge points, difficulty, and conclusion unchanged.</edit_principle>\n"
        "\n"
        "<latex_rules><!-- LaTeX formula-format mandatory rules -->\n"
        "  <delimiter>Inline formulas: \\(...\\). Display formulas: \\[...\\]. Do not use $...$, $$...$$, \\begin{equation}, \\begin{align}, or similar delimiters.</delimiter>\n"
        "  <standard_notation>\n"
        "    Fractions: \\frac{a}{b}. Radicals: \\sqrt{n}, \\sqrt[3]{x}. Superscripts/subscripts: x^{2}, a_{n}; even single characters must use braces.\n"
        "    Vectors: \\vec{a}, \\overrightarrow{AB}. Limits: \\lim_{n \\to \\infty}. Sums: \\sum_{i=1}^{n}. Integrals: \\int_{a}^{b}.\n"
        "    Greek letters: \\alpha, \\beta, \\theta, \\lambda, \\pi, etc. Do not use Unicode Greek letters.\n"
        "    Sets: \\in, \\subset, \\subseteq, \\cup, \\cap, \\emptyset, \\mathbb{R}.\n"
        "    Logic: \\Rightarrow, \\Leftrightarrow, \\forall, \\exists, \\neg.\n"
        "    Trigonometric functions: \\sin, \\cos, \\tan, \\cot. Logarithms: \\ln, \\lg, \\log_{a}.\n"
        "    Combinations/permutations: \\binom{n}{k} or C_{n}^{k}, A_{n}^{k}.\n"
        "  </standard_notation>\n"
        "  <structure>Tables/matrices/piecewise functions/case analysis must use array/matrix/cases environments. Do not use plain-text vertical layout; use aligned for multi-line derivations.</structure>\n"
        "  <integrity>All braces, parentheses, and brackets must be paired and closed. Do not use image formulas, MathML, or SVG.</integrity>\n"
        "</latex_rules>\n"
        "\n"
        "<answer_strictness>\n"
        "  The answer field must provide the complete final result. Do not use omissions such as 'omitted' or 'see analysis'. The analysis conclusion must match answer symbol-by-symbol.\n"
        "  Each derivation step must have theorem/formula support. Do not use skipped-step wording such as 'obvious'.\n"
        "</answer_strictness>\n"
        "<tool_usage>If the rewrite involves numerical calculation or equation solving, call python_scientific_compute to verify before output.</tool_usage>\n"
        "<verification>After rewriting, verify answer correctness and ensure derivation is correct and conclusion is fully consistent with the other fields.</verification>\n"
        "<output_format>Output a strict JSON object only. Do not output Markdown or explanations.</output_format>"
    )

    return [
        {"role": "system", "content": system_content},
        {"role": "user", "content": json.dumps(payload, ensure_ascii=False)},
    ]


async def regenerate_question_section(
    *,
    subject: str,
    topic: str,
    difficulty: str,
    question_type: str,
    study_markdown: str,
    section_key: str,
    stem: str,
    answer: str,
    analysis: str,
) -> str:
    if not is_llm_configured():
        return ""

    messages = build_regenerate_section_messages(
        subject=subject,
        topic=topic,
        difficulty=difficulty,
        question_type=question_type,
        study_markdown=study_markdown,
        section_key=section_key,
        stem=stem,
        answer=answer,
        analysis=analysis,
    )

    text = await _chat_json_with_reasoning(
        messages=messages,
        model=str(LESSON_PLAN_MODEL or "").strip() or "openai/gpt-5-mini",
        temperature=float(LESSON_PLAN_TEMPERATURE),
        max_tokens=0,
        req_id_prefix="qlr",
        retries=3,
        raise_on_fail=False,
        stage_id="draft_realization",
        stage_label="练习包生成",
        stream_reasoning=False,
        on_reasoning_event=None,
    )

    obj = _extract_json_obj(text)
    content = str(obj.get("content") or "").strip()
    if content:
        return content

    fallback_key = str(section_key or "").strip()
    if fallback_key in {"stem", "answer", "analysis"}:
        return str(obj.get(fallback_key) or "").strip()
    return ""
