"""Split a monolithic openapi-typescript output into per-domain files.

The single ``frontend/src/api/__generated__.ts`` file generated by
``openapi-typescript`` reaches ~10k lines and has measurable IDE / hot-reload
overhead. This script post-processes the file into:

- ``frontend/src/api/__generated__/<domain>.ts`` — paths typed for that domain
- ``frontend/src/api/__generated__/components.ts`` — shared components / schemas
- ``frontend/src/api/__generated__/index.ts`` — barrel re-export so existing
  imports (``@/api/__generated__``) keep working.

Domain mapping is based on URL prefixes (matching the canonical backend
boundaries described in ``docs/ARCHITECTURE.md``):

- ``system`` – ``/api/system/...``
- ``auth`` – ``/api/auth/...``
- ``workspace`` – conversations, papers, blueprints, study-archives,
  templates, annotations, feedback, item-meta, learning-plans, wrongbook,
  canvas, chat
- ``generation`` – deepthink, lesson-plans, study-materials, question-library,
  question-evaluate, essay-evaluations, knowledge-videos
- ``tasks`` – ``/api/tasks/...``
- ``integrations`` – crawler, subjects, media, share-links, exports
- ``misc`` – anything that did not match the above (kept for forward-compat)

Usage::

    python scripts/split_openapi_types.py \
        --src frontend/src/api/__generated__.ts \
        --out frontend/src/api/__generated__

The script is idempotent and safe to commit alongside the generated source.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Dict, List, Tuple

DOMAIN_RULES: List[Tuple[str, List[str]]] = [
    ("system", ["/api/system"]),
    ("auth", ["/api/auth"]),
    ("tasks", ["/api/tasks"]),
    (
        "generation",
        [
            "/api/deepthink",
            "/api/lesson-plans",
            "/api/study-materials",
            "/api/question-library",
            "/api/question-evaluate",
            "/api/essay-evaluations",
            "/api/knowledge-videos",
        ],
    ),
    (
        "workspace",
        [
            "/api/conversations",
            "/api/chat",
            "/api/canvas",
            "/api/papers",
            "/api/blueprints",
            "/api/study-archives",
            "/api/templates",
            "/api/annotations",
            "/api/feedback",
            "/api/item-meta",
            "/api/learning-plans",
            "/api/wrongbook",
            "/api/dashboard",
            "/api/user-settings",
        ],
    ),
    (
        "integrations",
        [
            "/api/crawler",
            "/api/subjects",
            "/api/media",
            "/api/share-links",
            "/api/share",
            "/api/exports",
            "/api/model-settings",
            "/api/search",
        ],
    ),
]


PATH_BLOCK_RE = re.compile(r'^( {4})"(?P<path>[^"]+)": \{', re.MULTILINE)


def _domain_for_path(path: str) -> str:
    for domain, prefixes in DOMAIN_RULES:
        for prefix in prefixes:
            if path == prefix or path.startswith(prefix + "/") or path.startswith(prefix + "{"):
                return domain
    return "misc"


def _extract_paths_block(source: str) -> Tuple[str, str, str]:
    """Return ``(before, paths_body, after)`` slicing the ``paths`` interface."""

    start = source.find("export interface paths {")
    if start < 0:
        raise SystemExit("Could not locate 'export interface paths {' in source.")
    body_start = source.find("{", start) + 1
    depth = 1
    i = body_start
    while i < len(source) and depth > 0:
        if source[i] == "{":
            depth += 1
        elif source[i] == "}":
            depth -= 1
        i += 1
    body_end = i  # right after closing '}'
    return source[:start], source[body_start:body_end - 1], source[body_end:]


def _split_path_blocks(paths_body: str) -> Dict[str, List[str]]:
    """Group each top-level path block by ``_domain_for_path``."""

    by_domain: Dict[str, List[str]] = {}
    matches = list(PATH_BLOCK_RE.finditer(paths_body))
    if not matches:
        return by_domain

    boundaries = [m.start() for m in matches] + [len(paths_body)]
    for idx, m in enumerate(matches):
        block = paths_body[boundaries[idx] : boundaries[idx + 1]]
        path = m.group("path")
        domain = _domain_for_path(path)
        by_domain.setdefault(domain, []).append(block)
    return by_domain


def split(*, src: Path, out_dir: Path, delete_source: bool = False) -> None:
    source = src.read_text(encoding="utf-8")
    before, paths_body, after = _extract_paths_block(source)
    by_domain = _split_path_blocks(paths_body)

    out_dir.mkdir(parents=True, exist_ok=True)

    # 1) components.ts: everything outside the paths interface.
    components = before.rstrip() + "\n" + after.lstrip()
    components_path = out_dir / "components.ts"
    components_path.write_text(
        "// AUTO-GENERATED. Do not edit by hand.\n"
        "// Components / schemas / operations + non-paths declarations.\n"
        "// Regenerate via `npm run gen:api`.\n\n"
        + components,
        encoding="utf-8",
    )

    # 2) per-domain path files.
    domain_module_names: List[str] = []
    for domain, blocks in sorted(by_domain.items()):
        domain_module_names.append(domain)
        body = "".join(blocks)
        text = (
            "// AUTO-GENERATED. Do not edit by hand.\n"
            f"// Paths for the `{domain}` domain.\n"
            "// Regenerate via `npm run gen:api`.\n\n"
            "import type { components, operations } from './components'\n\n"
            "export type { components, operations }\n\n"
            "export interface paths {\n"
            f"{body.rstrip()}\n"
            "}\n"
        )
        (out_dir / f"{domain}.ts").write_text(text, encoding="utf-8")

    # 3) barrel index keeping ``@/api/__generated__`` import path stable.
    barrel_lines = [
        "// AUTO-GENERATED. Do not edit by hand.",
        "// Barrel re-export so legacy imports of `@/api/__generated__` keep working.",
        "// Domain-specific imports should target `@/api/__generated__/<domain>` instead.",
        "",
        "export type { components, operations } from './components'",
        "export type { paths } from './paths'",
        "",
    ]
    for name in domain_module_names:
        barrel_lines.append(f"export type {{ paths as {name}Paths }} from './{name}'")
    (out_dir / "index.ts").write_text("\n".join(barrel_lines) + "\n", encoding="utf-8")

    # 4) merged paths.ts so the legacy `paths` interface still compiles.
    merged_lines = [
        "// AUTO-GENERATED. Do not edit by hand.",
        "// Merged `paths` interface mirroring the original monolithic file.",
        "",
        "import type { components, operations } from './components'",
        "",
        "export type { components, operations }",
        "",
        "export interface paths {",
        paths_body.rstrip(),
        "}",
        "",
    ]
    (out_dir / "paths.ts").write_text("\n".join(merged_lines) + "\n", encoding="utf-8")

    # 5) Optionally remove the monolithic file once the split has succeeded.
    # Keeping it around alongside the directory of the same name confuses
    # TypeScript's module resolution (and causes ambiguous imports), so
    # ``--delete-source`` is the recommended workflow when wired into CI.
    if delete_source:
        try:
            src.unlink(missing_ok=True)
        except OSError:
            pass


def main() -> None:
    parser = argparse.ArgumentParser(description="Split openapi-typescript output by domain.")
    parser.add_argument("--src", required=True, type=Path, help="Path to the monolithic generated file.")
    parser.add_argument("--out", required=True, type=Path, help="Output directory for split files.")
    parser.add_argument(
        "--delete-source",
        action="store_true",
        help="Remove the monolithic source file after a successful split.",
    )
    args = parser.parse_args()
    split(src=args.src, out_dir=args.out, delete_source=args.delete_source)


if __name__ == "__main__":
    main()
